version: '3.8'

# removed ports from frontend and backend
services:
  frontend:
    image: frontend
    command: ["serve", "-s", "-l", "5000", "build"]
  backend:
    image: backend
    command: ["./server"]
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=secret
    depends_on:
      - db
  redis:
    image: redis
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./datadir:/var/lib/postgresql/data
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_PORT=80
    restart: unless-stopped
