version: '3.8'

services:
  frontend:
    image: example-frontend
    ports:
      - 5000:5000
    command: ["serve", "-s", "-l", "5000", "build"]
  backend:
    image: example-backend
    ports:
      - 8080:8080
    command: ["./server"]
