version: '3.8'

services:
  frontend:
    image: frontend
    ports:
      - 5000:5000
    command: ["serve", "-s", "-l", "5000", "build"]
  backend:
    image: backend
    ports:
      - 8080:8080
    command: ["./server"]
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=secret
    depends_on:
      - db
  redis:
    image: redis
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./datadir:/var/lib/postgresql/data
